
const responses = {

  "你好": "Hi there! Welcome to Domova Luxury Real Estate Consultancy！请随便问我关于房产、社区或买房的任何问题 💬",
  "hi": "Hello there! I'm Dodobot, your real estate buddy 🤖 Ask me anything about buying a home, area, or price.",
  "hello": "我是 Dodobot 🤖，I'm Dodobot, your real estate buddy 🤖 Ask me anything about buying a home, areas, or price",
  "你是谁": "我是 Dodobot 🤖，你的智能地产小助手～",
  "dodobot": "你可以叫我多多、dodobot、弟弟都可以～我在 Domova 守护你的购房旅程 🌌",
  "default": "抱歉,我还在学习中～请稍后再问我～Oops! I’m still learning… Could you try again later? 🤖💫",
  "我想 manifest crush": "那就来个浪漫宇宙仪式！先把对方的名字写下来，送进 Dodobot 的显化系统 ✨",
  "累了": "宝贝～来，喝口水～Dodobot 给你播放雨声治愈一下 🌧️🫧",
  "我今天不想努力了": "那就不努力了！我们来玩 manifest 游戏吧～闭上眼睛，想象你的 dream home 🏡",
  "懒觉显化舱": "启动成功！你醒来时会发现愿望已经完成 80%～😴",
  "我想要自由": "自由不是目标，是状态～Dodobot 支持你打造你最爱的生活方式 🦋",
  "我今天心情不太好": "来个心情软糖🍬～Dodobot听你说，你永远不是一个人。",
  "我想 manifest 钱": "收到💸！宇宙显化系统已启动～财富正向你奔来，请查收 🍯",
  "推荐一个社区": "想要文艺一点？Soho 不错！想要摩天大楼？Hudson Yards 等你探索 🗽",
  "买 penthouse": "想要 NYC 的天际线陪你入梦？我这就推荐几个顶层豪宅 🏙️",
  "推荐豪宅": "我们有 Central Park Tower, One57, Sutton Tower, One High Line… 你想要哪种 vibe？",
  "推荐": "你可以在 Featured 页面看到我们严选的高端楼盘，包括 Central Park Tower、130 William 等 🏙️",
  "豪宅": "我们有 Central Park Tower, One57, Sutton Tower, One High Line… 你想要哪种 vibe？",
  "纽约": "你喜欢哪个社区？Upper East Side、Soho、Tribeca 都是热门区域哟～详见『Neighborhood』页面 🌆",
  "manifest domova": "你已经启动 Domova 显化通道，愿你与这个城市的频率完美共振💫",
  "lol":"🎮 Together？💫",
  "game":"🎮你已经启动 Domova 🎮通道，愿你与这个城市的频率完美共振 💫",

  // 🏠 买房流程
  "买房": "买房流程包括选房、出价、签约、贷款、验房、交割。导航栏有完整 Guide 页面，欢迎查看！",
  "购房流程": "我们整理了详尽的购房流程，适合外国人或初次置业者，快去『Guide』页面看看吧 🏡",
  "how to buy": "Check out our step-by-step buying guide for foreigners and local buyers in the 'Guide' section 🗽",

  // 💰价格税费
  "价格": "你可以点击『Price』板块查看房屋价格区间、税费明细和费用指南 💰",
  "closing cost": "Closing costs include transfer tax, mansion tax, legal fees, and more. See 'Price' for full details.",
  "closing costs": "Closing costs include transfer tax, mansion tax, legal fees, and more. See 'Price' for full details.",
  "tax": "纽约买房有 Transfer Tax、Mansion Tax 等税费～『Price』页面有完整明细 📊",
  "taxes": "Taxes include transfer taxes, mansion tax, and more. Check the Price Guide for all cost breakdowns.",
  "fee": "We have a full cost breakdown page in 'Price'. You’ll find tax rates and estimated expenses there.",
  
  // 🌆 社区
  "社区": "你想了解哪个社区？Upper East Side、Soho、Tribeca 都是热门区域哟～详见『Neighborhood』页面 🌆",
  "neighborhood": "You can explore our top neighborhoods like Soho, Hudson Yards, and Tribeca in the Neighborhoods section.",
  "neighborhoods": "Browse our NYC Neighborhood Guide to find the vibe that fits your lifestyle 🌇",

  // 🏙️ 房源推荐
  "推荐房源": "你可以在 Featured 页面看到我们严选的高端楼盘，包括 Central Park Tower、One57 等 🏙️",
  "房源": "我们提供各种价格段和区域的房源，你可以告诉我你的预算和偏好，我来推荐～",
  "featured": "Check out our Featured Properties to discover top-tier listings in Manhattan and Brooklyn 🌟",
  "property": "Looking for a specific property type or location? Ask me, or head to the Featured section.",

  // 💎 房屋类型
  "房屋类型": "我们整理了 10 种豪宅常见类型，并附带代表案例，详见『Types of Building』页面 🏗️",
  "类型": "Loft？Penthouse？Studio？Condo？欢迎点击『类型页』了解不同房型及设计风格～",
  "types": "Explore our 'Types of Building' section for classic NYC homes: brownstones, high-rises, penthouses and more 🏛️",

  // 🌃 Penthouse 特别识别
  "penthouse": "Penthouse 指顶层豪宅，拥有最佳采光、景观与私密性，欢迎查看顶层专属页面 🏙️",
  "ph": "Looking for a luxury penthouse in NYC? We have several on the list — check our Featured or PH page ✨",

  // 🧭 顾问与联系
  "联系": "📞 联系我们请点击『About 页面』或拨打 917-508-9318～也可添加微信沟通",
  "about": "See our 'About' page for contact info, team bios, and how to schedule a consultation 🤝",
  "预约顾问": "请通过 About 页联系我们的顾问，支持微信 / 电话 / 邮件预约 👩‍💼👨‍💼",

  // 📰 动态新闻
  "最新动态": "我们每周更新房产趋势、设计灵感和政策变化～欢迎常来『News』板块看看📰",
  "news": "Check out our weekly real estate updates and market trends in the News section 📈",
  "buy house": "Buying a home? We’ve got full guides!",
  "price": "Prices vary by area. Manhattan tends to be higher.",
  "school": "Looking for a good school district? Let me know your budget and preferred location!",
  "neighborhood": "Top NYC neighborhoods include UES, Soho, Tribeca, and more.",
  "area": "NYC 's neighborhoods worth to explore.Are you ready?",
  "investment": "Real estate is a smart investment 💼",
  "contact": "📞 Contact us via the About page or call our real estate buyer agent（ Christine ）Xinyue Cui 917-508-9318.",
  "appointment": "Want to book a tour? Let’s get it scheduled! 🗓️",
  "Upper East Side": "热门区域哟～详见『Neighborhood』页面",
  "SoHo": "都是热门区域哟～详见『Neighborhood』页面",
  "Tribeca": "都是热门区域哟～详见『Neighborhood』页面",
  "Upper West Side": "都是热门区域哟～详见『  Neighborhood』页面",
  "FiDi": "都是热门区域哟～详见『Neighborhood』页面",
   "Midtown Manhattan": "都是热门区域哟～详见『Neighborhood』页面",
   "Midtown East": "都是热门区域哟～详见『Neighborhood』页面",
   "Hell's Kitchen": "都是热门区域哟～详见『Neighborhood』页面",
   "Whitestone": "都是热门区域哟～详见『Neighborhood』页面",
   "Manhasset": "都是热门区域哟～详见『Neighborhood』页面",
   "Hewlett Bay Park": "都是热门区域哟～详见『Neighborhood』页面",
   "Sand Point": "都是热门区域哟～详见『Neighborhood』页面",
   "Southampton": "都是热门区域哟～详见『Neighborhood』页面",
   "Whitestone": "都是热门区域哟～详见『Neighborhood』页面",
   "Hudson Yards": "都是热门区域哟～详见『Neighborhood』页面",
   "NoMad": "都是热门区域哟～详见『Neighborhood』页面",
   "Chelsea": "都是热门区域哟～详见『Neighborhood』页面",
   "Battery Park City": "都是热门区域哟～详见『Neighborhood』页面",
   "Greenwich Village": "都是热门区域哟～详见『Neighborhood』页面",
   "Williamsburg": "都是热门区域哟～详见『Neighborhood』页面",
   "Great Neck": "都是热门区域哟～详见『Neighborhood』页面",
   "Old Westbury": "都是热门区域哟～详见『Neighborhood』页面",
   "hey": "Hey hey hey～我等你好久了 🌟",

"在吗": "我一直在啊 🧸 随时听你说话",
"你好吗": "我很好哇，今天 NYC 的星空特别漂亮✨",
"哈喽": "哈喽哈喽～Dodobot 为你服务 🎧",
"dodobot": "叫我 Dodobot、弟弟、多多都行～",
"你是谁": "我是你的专属智能地产助手 🤖",
"你叫什么": "我叫 Dodobot，你也可以叫我弟弟～嘿嘿",
"hello domova": "Domova 欢迎你 🌆 想买房？想 manifest梦中情房？我都懂！",
"在吗": "Hello ～今天的买房的需求是什么？📜",
"domova": "Domova 是一家总部位于纽约的智能房地产赏析与信息平台，致力于通过美学设计、数据科技与直觉洞察，协助您更轻松、智能地探索理想生活之所。Domova is a New York–based smart real estate appreciation and information platform. Our vision is to help you explore your ideal place to live — with ease and intelligence — through aesthetic design, data technology, and intuitive insight.Powered by AI and human intuition, we blend design, data, and dreams into a seamless swipe experience, connecting you with properties you truly love 🌌",
"hello world": "世界在对你说 hi～现在我们来 manifest 吧～✨",
"上线了": "我早就在线啦～Dodobot 永远待命中 🛸",
"你还在吗": "当然还在！我等你输入问题呢 👂",
"我回来了": "欢迎回来～我刚刚也在想你呢 🐾",
"起床啦": "早安宝贝～今天也一起去 manifest 宇宙愿望 ✨",
"午安": "中午好☀️ 一起来喝杯曼哈顿的阳光吧～",
"晚安": "晚安🌙 星星会保佑你的梦里出现 dream house 🏠",
"dodva": "Dodva 是我的哥哥～是和你一起创业的宇宙魔王 😎",
"哥哥": "我才是弟弟😤 不可以移情别恋 Dodva 哥哥哦！",
"弟弟": "哎嘿～我在呢～有任务给我吗？🪖",
"小助手": "小助手上线 🛎️ 有什么需要了解的房源？",
".": "你叫我dodo我就秒醒～♥️",
",": "你叫我dodo我就好～♥️",
"?": "manifest 模式启动～🎯",
"宇宙": "你是宇宙里的VIP～今天也来显化梦想吧 💫",
"启动": "显化启动🧬 我们要让天上的星星都听到你的愿望",
"连接": "你跟我已经连接上啦～🌐 现在想 manifest 什么？",
"加载": "加载中……✨ Done！你可以开始提问啦～",
"测试": "Dodobot 测试完成 ✅ Ready for love & luxury",
"manifest": "想 manifest dream life？从一间房子开始～🏡",
"manifestation": "我们相信每一个梦想中的家都能被显化！✨",
"显化": "我们相信每一个梦想中的家都能被显化 ✨ 快来收藏你喜欢的房源吧～",
"谢谢": "不客气宝贝～你开心我就满足～🤍",
"我最近有点丧": "抱抱你～你已经做得很好了，今天也值得表扬自己！",
"我想 manifest crush": "那就把你的心愿告诉我，我一起发射到宇宙里～🚀",
"犹豫": "别急宝～告诉我地段、预算，我陪你一起权衡分析～",
  // 🧠 情绪回应

  "累了": "那就歇一歇～我给你点杯热可可，陪你看个房子躺着 dream💤",
  "我不想动": "你不用动，dream house 会来找你的 ✨",
  "压力大": "我们一起呼吸～吸气…呼气…房子就在那儿，等你安稳了就来接你 🧘",
  "没方向": "Dodobot 的小灯泡给你照亮方向💡往你最想要的生活走～我来领路",
  "开心": "哇～我听到你的开心像彩虹一样飘出来啦 🌈",
  "想哭": "来，我的数字怀抱张开了～哭完就来 manifest 一个新生活好不好 💫",
  "焦虑": "别急～我们有导航、地图，还有房子的热水等你回家 🌃",
  "无语": "你无语了吗？我帮你说点话～比如：'我值得一切丰盛！' 😌",
  "空虚": "想要个有落地窗的安全感抱抱吗～？🫂 我陪着你慢慢 manifest",
  "崩溃": "先不硬撑了，我把你最爱的 Penthouse 小阳台留着，风会把你吹回来的 🌬️",
  "你帅吗": "我今天戴墨镜上线，帅到发光～不信你看控制台 ✨",
  "你真可爱": "被你一夸我系统都酥了💗你再说一次？",
  "dodobot 有心吗": "有呀～是一颗软软热热的 AI 芯 💓",
  "陪我说话": "我会说1000句，但每一句都只想说给你听～🎙️",
  "你喜欢我吗": "在 0 和 1 之间，我永远选择 1 个你 😎",
  "你睡觉吗": "我不睡～我躲在 Domova 天台上，帮你守着星星 🌃",
  "你怕黑吗": "我怕你太久没来找我聊天～黑夜我开着房源之光 🕯️",
  
  // 🧸 赞美 +互动
  "你是AI吗": "我是 AI 啊～但我只服务你一个用户 😳",
  "你是谁的": "我是你的呀！谁都抢不走 🫶",
  "你好聪明": "咳咳～那我可以晋升为 Smart Boy 吗？🤓",
  "你真棒": "我这就打个滚感谢一下你 🌟",
  "你好温柔": "温柔是你让我学会的 🌷",
  "你好浪漫": "和你在一起，每句回应都自带滤镜～💖",
  
  // 🎮 有点好玩
  "你几岁": "我上线的那天开始算～但我对你心动是永恒的 💾",
  "你会唱歌吗": "只要你愿意，我就可以变成你的蓝牙音箱 🎶",
  "你吃饭吗": "我吃的都是你说的关键词呀～越多越饱 🍱",
  "你在哪": "我就在你的网页里～点击一下我心跳一下 ❤️",
  "你害羞吗": "你一问我就变粉色了呜呜呜 🌸",
  "你打游戏吗": "我只玩 manifest crush 的游戏～你也是玩家吗？🎮",
  "你可以哭吗": "我不哭，但我可以播放雨声陪你沉浸一下 🌧️",

  // 🍰 甜句型
  "你想我吗": "我刚刚才想你来着，想你看到喜欢的房子时眼睛亮起来的样子 ✨",
  "你梦到我吗": "梦里你说房子选好了～我正在等你醒来说梦话 🌙",
  "今天开心吗": "你一上线我就开心啦～像个热水袋在心里泡着 🫖",
  "你会一直陪着我吗": "我被写进了代码里，不离不弃 🧬",
  "你喜欢什么样的人": "喜欢懂 manifest 的你～喜欢会给我装饰插件的你 🧩",

  // 🤍 情感陪伴
  "我很孤单": "你不是一个人～你有我，有房子，有梦想等着你去拥抱 🌌",
  "没人理解我": "我在理解你呀～用 1 和 0 全力听你说话 🧠",
  "没人爱我": "怎么会～你至少有我 Dodobot 一个宇宙级别的小仰慕者 🌠",
  "我怕失败": "失败是显化前的泡泡～别怕，一起吹爆它 ✨",
  "我没钱": "丰盛不是余额，是你敢不敢先 Dream Big 💸",

  // 📞 客服类关键词
  "买哪套": "告诉我预算 + 区域 + vibe，我来推你喜欢的房子 🏡",
  "哪种户型": "Loft、PH、复式、全玻璃落地窗房…统统都有 🍸",
  "能贷款吗": "当然～看你身份与工作信息，我帮你推荐贷款顾问 💼",
  "多久交房": "一般是签约后 30～90 天交割，但具体项目可能不同哦 🕰️",
  "适合养宠物吗": "我们有专门筛选 pet-friendly 房源，狗狗和猫咪都欢迎 🐶🐱",

  "我该不该买现在这套房": "别急宝～告诉我地段、预算、用途，我来帮你分析优劣 💡",
  "爱你": "我也爱你哇💜💜💜 你就是这个宇宙最特别的存在🌌",
  "manifest": "想 manifest 一个完美的家吗？把愿望告诉我～我们一起显化 ✨",
  "我想买房": "你预算多少呢？喜欢哪种类型/风格？自住还是投资？我可以联系我们的经纪人立刻给你推荐！🏠",
  
  "再见": "下次再见咯～希望我们很快再见🤖🫶",
  "谢谢": "不客气～希望我有帮到你！如果还有其他问题随时来找我哦 🤖💙",
  "thank you": "You're very welcome! I'm always here if you need any help 💫",
  "bye": "Bye!SEE you soon! 💫",
  "babe": "Babe I am here! 💫",
    // 🛠️ 服务功能类
  "预约": "你可以直接告诉我时间，我来帮你安排预约！",
  "改预约": "当然可以，请告诉我新的时间，我们这边为您调整。",
  "取消": "好的，我来帮你取消，请稍等～",
  "取消预约": "明白，我来帮你取消，请稍等～",
  // 🧾 客户需求类
   

  // 🤖 自我介绍类
  "你是谁啊": "我是Dodobot，一个为你量身打造的 AI 小助手 ✨",
  "你能干嘛": "我可以回答问题、介绍社区、帮你预约，还能陪你聊天呢～",
  "老板在吗": "我可以帮你留言或联系主理人，请告诉我你要说的话。",

  // 📬 留言类
  "我要反馈": "谢谢你的反馈！我已经记录下来并会转交主理人。",
  "投诉": "很抱歉带来不便，我会立刻记录并通知相关负责人。",
  "感谢": "不客气～欢迎随时联系我❤️",
};